### PR TITLE
readme.md Updated

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
image

issue #1

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
hi @kartikayasijaa review the PR

**Comment by RamakrushnaBiswal** [comment]
issue #11

**Comment by kartikayasijaa** [comment]
please make the introduction more technical, add about the tech stack, features etc.

**Comment by RamakrushnaBiswal** [comment]
I added tech. Stacks bellow of it

**Comment by RamakrushnaBiswal** [comment]
Screenshot_2024-06-18-18-11-07-97_40deb401b9ffe8e1df2f1cc5ba480b12
Screenshot_2024-06-18-18-11-12-69_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by kartikayasijaa** [comment]
image
Please change content for this, add technical details in it.
@RamakrushnaBiswal 

Else everything is great :)

**Comment by RamakrushnaBiswal** [comment]
hi @kartikayasijaa done

**Comment by kartikayasijaa** [comment]
@RamakrushnaBiswal What's your email?

**Comment by RamakrushnaBiswal** [comment]
@kartikayasijaa ramakrushnabunty@gmail.com

**Pull request merged**
